### ISSUE TITLE
Module version mismatch

### ISSUE THREAD

**Issue by abkfenris** [willwhitney/jupyter-notebook-atom#2]
Now that I've `npm installed` Atom is throwing a `Module version mismatch` while trying to load the package.

**Atom Version**: 1.0.3
**System**: Mac OS X 10.10.4
**Thrown From**: [jupyter-notebook](https://github.com/willwhitney/jupyter-notebook-atom) package, v0.0.1

### Stack Trace

Failed to load the jupyter-notebook package

```javascript
At Module version mismatch. Expected 43, got 14.

Error: Module version mismatch. Expected 43, got 14.
  at Error (native)
  at Object.module.(anonymous function) (ATOM_SHELL_ASAR.js:118:20)
  at Object.module.(anonymous function) (ATOM_SHELL_ASAR.js:118:20)
  at Object.module.(anonymous function) [as .node] (ATOM_SHELL_ASAR.js:118:20)
  at Module.load (module.js:347:32)
  at Function.Module._load (module.js:302:12)
  at Module.require (module.js:357:17)
  at require (module.js:376:17)
  at Object.<anonymous> (/Users/kerneya/Geek/jupyter-notebook-atom/node_modules/pathwatcher/lib/main.js:6:13)
  at Object.<anonymous> (/Users/kerneya/Geek/jupyter-notebook-atom/node_modules/pathwatcher/lib/main.js:207:4)
  at Module._compile (module.js:452:26)
  at Object.loadFile [as .js] (/Applications/Atom.app/Contents/Resources/app.asar/src/babel.js:162:21)
  at Module.load (module.js:347:32)
  at Function.Module._load (module.js:302:12)
  at Module.require (module.js:357:17)
  at require (module.js:376:17)
  at Object.<anonymous> (/Users/kerneya/Geek/jupyter-notebook-atom/lib/notebook-editor.js:19:12)
  at Module._compile (module.js:452:26)
  at Object.loadFile [as .js] (/Applications/Atom.app/Contents/Resources/app.asar/src/babel.js:166:19)
  at Module.load (module.js:347:32)
  at Function.Module._load (module.js:302:12)
  at Module.require (module.js:357:17)
  at require (module.js:376:17)
  at Object.<anonymous> (/Users/kerneya/Geek/jupyter-notebook-atom/lib/main.js:11:22)
  at Module._compile (module.js:452:26)
  at Object.loadFile [as .js] (/Applications/Atom.app/Contents/Resources/app.asar/src/babel.js:166:19)
  at Module.load (module.js:347:32)
  at Function.Module._load (module.js:302:12)
  at Module.require (module.js:357:17)
  at require (module.js:376:17)
  at Package.module.exports.Package.requireMainModule (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:715:34)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:190:28
  at Package.module.exports.Package.measure (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:167:15)
  at Package.module.exports.Package.load (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:181:12)
  at PackageManager.module.exports.PackageManager.loadPackage (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:373:14)
  at PackageManager.module.exports.PackageManager.enablePackage (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:141:19)
  at HTMLButtonElement.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-card.js:314:27)
  at HTMLButtonElement.jQuery.event.dispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/jquery/dist/jquery.js:4435:9)
  at HTMLButtonElement.elemData.handle (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/jquery/dist/jquery.js:4121:28)

```

### Commands

```
```

### Config

```json
{
  "core": {
    "ignoredNames": [
      ".git",
      ".hg",
      ".svn",
      ".DS_Store",
      "Thumbs.db",
      ".pyc"
    ],
    "disabledPackages": [
      "linter-pep8",
      "linter-python-pep8",
      "linter-python-pyflakes",
      "autocomplete-jedi",
      "python-coverage"
    ],
    "themes": [
      "solarized-dark-ui",
      "solarized-dark-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
Sublime-Style-Column-Selection, v1.3.0
atom-jinja2, v0.5.0
autocomplete-plus-python-jedi, v0.3.6
compare-files, v0.6.2
jupyter-notebook, v0.0.1
language-restructuredtext, v0.6.0
linter, v1.2.3
linter-flake8, v1.5.0
react, v0.12.6
solarized-dark-ui, v0.3.1

# Dev
No dev packages
```

**Comment by willwhitney** [comment]
You probably need to `apm rebuild` — let me know if that does it.

**Comment by rgbkrk** [comment]
Oh the woes of node-zmq rebuilds when Atom relaunches.

**Comment by willwhitney** [comment]
@rgbkrk what's the status of that Go zmq <-> websocket intermediary?

**Comment by abkfenris** [comment]
It's alive!

**Comment by rgbkrk** [comment]
[Have library](https://github.com/rgbkrk/juno), will travel. We need to figure out what we want and need (do we just stay compatible with the notebook kernels, sessions, etc. API?). 

Soon I'll try out [goczmq](https://github.com/zeromq/goczmq) as the supporting zmq library though, as I'm not sure how I feel about the reactor model with the current zmq library. hintjens seems to be active and involved in the development as well.

**Comment by abkfenris** [comment]
Uhh, yes travel. That's what I'm actually supposed to be doing right now not playing with new atom packages.

**Comment by willwhitney** [comment]
Yeah, but this is way more fun :wink: 

Glad it's working now!
